### ISSUE TITLE
No two-way synchronisation with SSO server when logging in

### ISSUE THREAD

**Issue by ernstkui** [lizardsystem/lizard-auth-client#25]
Originally reported by @byrman: https://github.com/nens/lizard-nxt/issues/1038

If a user logs on via the GUI, new organisations and roles are fetched from the SSO server. Removing a user from an organisation/role, however, is not properly propagated.

Steps to reproduce the problem:

1. Choose a test user on your portal.
2. On the SSO server, delete the test user from at least one existing organisation/role.
3. Log in to your portal via the GUI as test user.
4. Inspect table lizard_auth_client_userorganisationrole and notice that the corresponding organisation/role is not deleted for test user.

Compare this behaviour to:

1. Choose a test user on your portal.
2. On the SSO server, add the test user to at least one new organisation/role.
3. Log in to your portal via the GUI as test user.
4. Inspect table lizard_auth_client_userorganisationrole and notice that the corresponding organisation/role is added for test user.

Conclusion: it seems that new organisations/roles are synchronized, but deleted organisations/role are not. It doesn't seem like a caching problem to me, but rather a synchronisation issue.

**Comment by byrman** [comment]
Fixed via this PR: https://github.com/lizardsystem/lizard-auth-client/pull/27

**Comment by byrman** [comment]
Fixed in 1.7.1
