### ISSUE TITLE
Log level for authentication failure too high?

### ISSUE THREAD

**Issue by byrman** [lizardsystem/lizard-auth-client#34]
If a user provides a wrong username/password, this is logged as an exception and shows up in Sentry / logstash. I.m.h.o. it's not really an application error. Shouldn't a lower log level be more appropriate?

https://github.com/lizardsystem/lizard-auth-client/blob/master/lizard_auth_client/backends.py#L62
https://github.com/lizardsystem/lizard-auth-client/blob/master/lizard_auth_client/backends.py#L82

**Comment by reinout** [comment]
Info level would be fine.
