### ISSUE TITLE
Django 1.10 compatibility

### ISSUE THREAD

**Issue by byrman** [lizardsystem/lizard-auth-client#42]
We're preparing lizard-nxt for Django 1.10. One of the blockers is lizard-auth-client: its urls.py needs modification:

```
vagrant@nxt-server:/vagrant$ bin/django check
Using localsettings

WARNING /home/vagrant/.buildout/eggs/lizard_auth_client-1.13-py2.7.egg/lizard_auth_client/urls.py:83: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  name='lizard_auth_client.sso_local_logout'),
```

**Comment by byrman** [comment]
The fix itself is easy, but lizard-auth-client is still used by sites that run old Django versions.

**Comment by reinout** [comment]
We could look at a try/except. Or accept that older sites need an update, too. As long as it is compatible with django 1.8 (LTS), it is OK with me.

**Comment by reinout** [comment]
Old sites: I'll update TRS soon. Efcis is 1.7.8, so that might be a problem. Or actually, that might be something that needs updating to 1.8.

**Comment by reinout** [comment]
2.0.1 (well, wait for 2.1) should be fine.
