### ISSUE TITLE
Default for JWT_EXPIRATION_MINUTES?

### ISSUE THREAD

**Issue by byrman** [lizardsystem/lizard-auth-client#43]
Kan deze geen sensible default krijgen, zodat je niet wordt gedwongen om je settings aan te passen?

https://github.com/lizardsystem/lizard-auth-client/blob/master/lizard_auth_client/views.py#L35

**Comment by reinout** [comment]
5 minuten is volgens mij standaard. Dus: prima om te wijzigen.

**Comment by reinout** [comment]
Vergeten een branch te maken... Het zit in master.

**Comment by reinout** [comment]
En in versie 2.0.1

**Comment by reinout** [comment]
... maar het is niet de enige setting. Ik ga een django-appconf in gooien.

**Comment by byrman** [comment]
Top

2016-09-02 10:42 GMT+02:00 Reinout van Rees <notifications@github.com>:

**Comment by reinout** [comment]
Zie #45
