### ISSUE TITLE
SSO_SERVER_PRIVATE_URL

### ISSUE THREAD

**Issue by byrman** [lizardsystem/lizard-auth-client#47]
V2 zou SSO_SERVER_PRIVATE_URL toch obsolete moeten maken? M.a.w. dit zou toch voldoende moeten zijn (uit mijn localsettings.py):

```
SSO_USE_V2_LOGIN = True
SSO_SERVER_PUBLIC_URL_V2 = 'https://sso.staging.lizard.net/api/v2/'
```

Met bovenstaande settings kan ik echter niet inloggen:

```
INFO 10.0.3.1 - GET /api-auth/login/?next=/api/v2/ 200 2633 (0.01 seconds) (0 SQL queries, 0 ms)
[09/Sep/2016 13:40:55] "GET /api-auth/login/?next=/api/v2/ HTTP/1.1" 200 2633
DEBUG Could not find user "jordan.belfort" in the credential cache.
INFO Starting new HTTP connection (1): 110-sso-c1.external-nens.local
DEBUG "POST /api/authenticate/ HTTP/1.1" 200 None
DEBUG Data received in _do_post: {u'success': False, u'error': u'Login failed'}
INFO Login failed
```

Aan de output hierboven zie je dat er contact wordt gezocht met 110-sso-c1.external-nens.local (opgepikt uit mijn development settings). Wat mij verbaast is dat er blijkbaar nog wordt gewerkt op de oude manier, d.w.z. via de binnen- i.p.v. de buitenkant.

Als ik deze regel toevoeg:

```
SSO_SERVER_PRIVATE_URL = 'http://112-sso-d3.external-nens.local:5000/'
```

dan  kan ik wel inloggen.

**Comment by reinout** [comment]
Waar komt die `/api-auth/login/` vandaan?

**Comment by byrman** [comment]
![image](https://cloud.githubusercontent.com/assets/1039433/18388463/0a1239a4-76a2-11e6-82ac-3da028c2eda6.png)

**Comment by byrman** [comment]
Ik log in op de API (heb geen zin om lizard-client op te starten).

**Comment by reinout** [comment]
Ah. Ik heb het idee dat dit toch wel een TODO puntje is. Er zit een verschil tussen de loginview en de `backends.py`. Ik ga kijken.

**Comment by byrman** [comment]
V2 authenticatie gaat nu goed, ik kom dus succesvol langs deze regel:

https://github.com/lizardsystem/lizard-auth-client/blob/reinout-direct-login/lizard_auth_client/backends.py#L60

Niet veel verder gaat het echter fout op deze regel:

https://github.com/lizardsystem/lizard-auth-client/blob/reinout-direct-login/lizard_auth_client/backends.py#L81

Als je daarin in stapt kom je hier:

https://github.com/lizardsystem/lizard-auth-client/blob/reinout-direct-login/lizard_auth_client/client.py#L570

In deze aanroep wordt SSO_SERVER_PRIVATE_URL gebruikt. Onder V2 zou deze setting er niet toe doen, maar hij wordt dus toch gebruikt.

Maar ik denk dat we hier helemaal niet horen te komen: waarom `client.sso_sync_user_organisation_roles(user)` uitvoeren terwijl V2 helemaal geen organisation en roles kent. Moet het bijvoorbeeld niet zoiets worden?

```
# Use either the cached user profile data, or fresh data from
# the SSO server to construct a Django User instance. If
# fresh data is used, also synchronize roles (V1).
if user_data:
    user = client.construct_user(user_data)
    if not cached_credentials:
        if not settings.SSO_USE_V2_LOGIN:
            client.sso_sync_user_organisation_roles(user)
```

**Comment by reinout** [comment]
Op 13-09-16 om 15:27 schreef byrman:
> Maar ik denk dat we hier helemaal niet horen te komen: waarom
> |client.sso_sync_user_organisation_roles(user)| uitvoeren terwijl V2
> helemaal geen organisation en roles kent. Moet het bijvoorbeeld niet
> zoiets worden?

Ja, klopt. Gefixt.


Reinout

-- 
Reinout van Rees  http://reinout.vanrees.org/   reinout@vanrees.org
"Military engineers build missiles. Civil engineers build targets."
