### ISSUE TITLE
Er wordt naar het oude profiel gekeken tijdens het V2 inlogproces?

### ISSUE THREAD

**Issue by byrman** [lizardsystem/lizard-auth-client#48]
Ik heb de volgende acties uitgevoerd op sso.staging.lizard.net:

- Een nieuwe company aangemaakt: Stratton Oakmont.
- Een nieuwe gebruiker aangemaakt: Jordan Belfort (member van Stratton Oakmont).
- Een nieuwe site aangemaakt: Lizard NXT development (available to Stratton Oakmont).

Ik gebruikt de volgende localsettings:

```
SSO_USE_V2_LOGIN = True
SSO_SERVER_PUBLIC_URL_V2 = 'https://sso.staging.lizard.net/api/v2/'
SSO_SERVER_PRIVATE_URL = 'http://112-sso-d3.external-nens.local:5000/'
```

Ik kan nu niet inloggen en krijg dit in mijn console:

```
DEBUG "POST /api/authenticate/ HTTP/1.1" 200 None
DEBUG Data received in _do_post: {u'success': False, u'error': u'No access to this portal'}
INFO No access to this portal
```

Ik ga naar Jordan's _oude_ profiel en geeft hem daar toegang tot Lizard NXT development. Nu kan ik _wel_ inloggen.

Ik ga naar Jordan's _oude_ profiel en verwijder hem uit Lizard NXT development. Nu kan ik _niet_ inloggen.

Conclusie: ik gebruik V2 settings, maar er wordt naar het oude profiel gekeken tijdens het inlogproces?

**Comment by reinout** [comment]
Kan je met `bin/django diffsettings` checken of de use-v2-login wel overkomt?

Onderin `views.py` staat een if/else die `LoginView` naar de juiste versie zet. Kun je met `bin/django shell` kijken of `JWTLoginView` gelijk is aan `LoginView`?

**Comment by byrman** [comment]
```
SSO_KEY = 'u2pLw5zDCGuJ9tYeezfsZCgp05G087VknbDy05V5Cn0bO98aT5elgksQzI9Hv9z2'  ###
SSO_SECRET = ...  ###
SSO_SERVER_PRIVATE_URL = 'http://112-sso-d3.external-nens.local:5000/'  ###
SSO_SERVER_PUBLIC_URL = 'http://sso.lizard.net/'  ###
SSO_SERVER_PUBLIC_URL_V2 = 'https://sso.staging.lizard.net/api/v2/'  ###
SSO_USE_V2_LOGIN = True  ###
```

**Comment by byrman** [comment]
```
In [1]: from lizard_auth_client.views import LoginView

In [2]: LoginView
Out[2]: lizard_auth_client.views.JWTLoginView
```

**Comment by reinout** [comment]
Zelfde issue als #47: de login pagina is aangepast, maar het standaard django inlog mechanisme (via de backend) nog niet. Als ik met dit in het achterhoofd de code bekijk lijken er een paar plekken te zijn waar het inloggen wordt geregeld. Zucht.
