### ISSUE TITLE
Default ordering of Organisations

### ISSUE THREAD

**Issue by byrman** [lizardsystem/lizard-auth-client#68]
Zou er iets op tegen zijn om dit toe te voegen aan het Organisation model?

```
class Meta:
    ordering = ('name', )
```

Ik kom namelijk vaak dit soort lijstjes tegen en het kost relatief veel moeite om dit goed te krijgen:

![image](https://user-images.githubusercontent.com/1039433/29075722-9a166658-7c53-11e7-8eb8-5b5958de1bc2.png)

**Comment by reinout** [comment]
Lijkt me dat daar niets tegen is. Misschien ook even in lizard-auth-server kijken wat daar nog aan eventuele handige order/admin zaken staat.

(Ongerelateerd: uit leesbaarheid gebruik ik zelf trouwens lijsten ipv tuples, dus `ordering = ['name']` in dit geval. Volgens mij is dat inmiddels ook de standaard in Django.)

**Comment by byrman** [comment]
https://github.com/lizardsystem/lizard-auth-client/blob/master/lizard_auth_client/models.py#L80
