### ISSUE TITLE
Django 2.1

### ISSUE THREAD

**Issue by byrman** [lizardsystem/lizard-auth-client#81]
The latest official Django version is 2.1.4. According to buildout.cfg, the current version of lizard-auth-client was written with Django 1.8 in mind:

https://github.com/lizardsystem/lizard-auth-client/blob/master/buildout.cfg#L26

The code needs an overhaul to support modern Django. For example:

- Middleware needs to be fixed: https://docs.djangoproject.com/en/2.1/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware
- user.is_authenticated() is no longer a function but a property.
- Etc.

**Comment by reinout** [comment]
Met die middleware mixin van django lijkt de middleware makkelijk te fixen.
De is_authenticated() zou een lastige kunnen zijn, maar ik kan me niet voorstellen dat django er geen trucje voor heeft. En anders moeten we het major versienummer van lizard-auth-client maar weer eens ophogen.

Misschien daarvoor nog een release maken van de huidige versie met "Django < 2.0" in de `install_requires` lijst?

**Comment by byrman** [comment]
https://github.com/lizardsystem/lizard-auth-client/pull/83
