### ISSUE TITLE
Change user and organisation field to searchable pk-fields in admin

### ISSUE THREAD

**Issue by lexvand** [lizardsystem/lizard-auth-client#90]
In Lizard admin it becomes harder to manage user organisation roles, because the lists of usernames and organisations grow. Change these fields to primary key fields with search option to make it easier to add roles.

Current situation:
![image.png](https://images.zenhubusercontent.com/5ede3192cc5c2c4503d452e7/5d45842d-5268-4964-ad87-e3713207b52c)

Example of desired field type (e.g. raster sources):
![image.png](https://images.zenhubusercontent.com/5ede3192cc5c2c4503d452e7/cf95c81f-ab82-4d1b-832e-d8b755e3697b)

**Comment by lexvand** [comment]
@caspervdw This repo is EOL by the end of the year, right? In that case we should not change this anymore. Some other place we could improve the manageability of user organisation roles?

**Comment by caspervdw** [comment]
Indeed the authentication part (SSO interface) will become EOL. But the _authorization_ part (Organisations, Roles, UORs) are also in lizard-auth-client.

I'd propose moving the authorization models into the lizard repo, and then start changing stuff like the admin page.
