### ISSUE TITLE
Show `created` in detail view of organisations in Django admin

### ISSUE THREAD

**Issue by lexvand** [lizardsystem/lizard-auth-client#91]
Based on a wish from application management. With the growth in the number of organisations and different people that administrate them it is useful for application managers to know when an organisation was created. Currently, that can only be found in the API or in the database. It would help if it can be found in the admin as well.

**Comment by reinout** [comment]
Shouldn't this go into **nens**-auth-client?

**Comment by lexvand** [comment]
Issue moved to [nens/nens-auth-client #72](https://github.com/nens/nens-auth-client/issues/72) via [**ZenHub**](https://www.zenhub.com/)
