### ISSUE TITLE
Make it easier to find user and organisation when setting roles in Django Admin

### ISSUE THREAD

**Issue by lexvand** [lizardsystem/lizard-auth-client#92]
When creating a UserOrganisationRole in Django admin you need to select the user and organisation from a dropdown, that only supports quick selection by a username__startswith search by starting to type in the standard Django `<select>` field. With the growing number of users and organisations this is becoming an increasingly difficult task.

What would help:
- Being able to search for the foreign key relation (like in a raw_id_field, but without loosing the quick option; is [this](https://docs.djangoproject.com/en/4.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.autocomplete_fields) an option?)
- By default filter out inactive users

**Alternative**: Automatically give manager rights to superusers, so they can use the Lizard management page for configuring user accounts and roles instead of the Django admin. 3Di already supports this, but it may be harder to fit in the Lizard authorisation system.

**Comment by lexvand** [comment]
@byrman What do you think about this issue?

**Comment by byrman** [comment]
> @byrman What do you think about this issue?

Yes, that Admin page has much to be desired. But is it still used? The same can be achieved by sending an invitation?

We can improve on the Admin page, but perhaps we should get rid of lizard-auth-client and move the concept of organisations and roles to Lizard? Most of the lizard-auth-client library is now obsolete?

> Automatically give manager rights to superusers

You propose that our superusers will have the manager role in each and every organisation? I don't like that very much. Preferably,  we should only be part of NENS, not of external organisations. (Do you see Amazon employees in our Cognito user pool?)

**Comment by lexvand** [comment]
Issue moved to [nens/nens-auth-client #73](https://github.com/nens/nens-auth-client/issues/73) via [**ZenHub**](https://www.zenhub.com/)
